package com.secbro.model;

import java.io.Serializable;

public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.id
     *
     * @mbg.generated Sun Mar 01 14:00:19 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.order_no
     *
     * @mbg.generated Sun Mar 01 14:00:19 CST 2020
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.amount
     *
     * @mbg.generated Sun Mar 01 14:00:19 CST 2020
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_order
     *
     * @mbg.generated Sun Mar 01 14:00:19 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.id
     *
     * @return the value of tb_order.id
     *
     * @mbg.generated Sun Mar 01 14:00:19 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.id
     *
     * @param id the value for tb_order.id
     *
     * @mbg.generated Sun Mar 01 14:00:19 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.order_no
     *
     * @return the value of tb_order.order_no
     *
     * @mbg.generated Sun Mar 01 14:00:19 CST 2020
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.order_no
     *
     * @param orderNo the value for tb_order.order_no
     *
     * @mbg.generated Sun Mar 01 14:00:19 CST 2020
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.amount
     *
     * @return the value of tb_order.amount
     *
     * @mbg.generated Sun Mar 01 14:00:19 CST 2020
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.amount
     *
     * @param amount the value for tb_order.amount
     *
     * @mbg.generated Sun Mar 01 14:00:19 CST 2020
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
}